services:

  postgres:
    image: postgres:16
    container_name: legal-document-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legal_documents

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: legal-document-backend
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      NODE_ENV: development

      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/legal_documents

      SOFFICE_PATH: /usr/bin/soffice

    ports:
      - "3000:3000"

    volumes:
      - backend_uploads:/app/uploads


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: legal-document-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  postgres_data:
  backend_uploads: